config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/", to: "home#index"

  get "/menu_categories", to: "menu_categories#index"
  post "/menu_categories", to: "menu_categories#create", as: :create_menu_category
  put "/menu_categories/:id", to: "menu_categories#update"
  delete "/menu_categories/:id", to: "menu_categories#destroy"

  get "/new_menu_item", to: "menu_items#new", as: :new_menu_item
  get "/create_menu_item", to: "menu_items#create", as: :create_menu_item
  put "/menu_items/:id", to: "menu_items#update"
  delete "/menu_items/:id", to: "menu_items#destroy"

  get "cart_items", to: "cart_items#index"
  post "cart_items", to: "cart_items#create"
  delete "/clear_cart_items", to: "cart_items#destroy", as: :cart_clear
  put "/cart_items", to: "cart_items#update", as: :update_quantity

  get "/orders", to: "orders#index"
  post "/orders/:total_amount", to: "orders#create"
  put "/orders/:id", to: "orders#update"

  get "/order_items", to: "order_items#index"
  get "/create_order_item", to: "order_items#create", as: :create_order_item

  resources :users

  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  get "/signout", to: "sessions#destroy", as: :destroy_session

  get "/reports", to: "reports#index", as: :reports
end

app/models/menu_category.rb
class MenuCategory < ActiveRecord::Base
  has_many :menu_items

  validates :name,
            presence: true,
            length: { minimum: 4 },
            uniqueness: { case_sensitive: false }

  def to_category
    "#{id}. #{name} | Available: #{status}"
  end
end

app/controllers/menu_categories_controller.rb
class MenuCategoriesController < ApplicationController
  def index
    @cart_items = @current_user.cart_items
    render "index"
  end

  def create
    category = MenuCategory.find_by(id: params[:category])

    unless category.present?
      new_category = MenuCategory.new(
        name: params[:newcategory],
        status: true,
      )
      unless new_category.save
        flash[:error] = "No category selected or created"
        redirect_to new_menu_item_path
      else
        if params[:name].present? && params[:price].present? && params[:description].present?
          redirect_to create_menu_item_path(
            menu_category_id: new_category.id,
            name: params[:name],
            price: params[:price],
            description: params[:description],
          )
        else
          flash[:success] = "New #{params[:newcategory]} Category created.\n Enter item details to add menu"
          redirect_to menu_categories_path
        end
      end
    else
      unless (params[:newcategory] == "")
        cachename = MenuCategory.find_by(id: params[:category]).name
        MenuCategory.find(category.id).update(name: params[:newcategory])
      end
      if params[:name].present? && params[:price].present? && params[:description].present?
        redirect_to create_menu_item_path(
          menu_category_id: category.id,
          name: params[:name],
          price: params[:price],
          description: params[:description],
        )
      else
        if (params[:newcategory] == "")
          flash[:error] = "No category updated"
          redirect_to new_menu_item_path
        else
          flash[:success] = "#{cachename} Category's name Updated to #{params[:newcategory]} .\n Enter item details to add menu"
          redirect_to new_menu_item_path
        end
      end
    end
  end

  def update
    menucategory = MenuCategory.find(params[:id])
    menucategory.status = !menucategory.status
    menucategory.save!
    flash[:success] = " \'#{menucategory.name}\' Category is #{menucategory.status ? "available" : " disabled"} ."
    redirect_to menu_categories_path
  end

  def destroy
    cachename = MenuCategory.find(params[:id]).name
    MenuCategory.find(params[:id]).destroy
    flash[:success] = "#{cachename} Category Deleted"
    redirect_to menu_categories_path
  end
end

app/views/menu_categories/_cartsection.html.erb
<section class="CartCategoryPage">
    <p class="MenuTitle">Cart</p>





    <% if @cart_items.present? %>
        <div class ="Cart-section">
            <% @cart_items.order(:created_at).each do |cartitem| %>
                <% item = MenuItem.find(cartitem.menu_item_id) %>


                    <div class="CartItem-section">

                        <span class="MenuItem-title">
                            <%= item.name %>
                        </span>

                        <div class="CartQuantity">
                            <%= form_with(url: update_quantity_path(id: cartitem.id, quantity: -1),
                                          method: "PUT") do %>
                                <%= submit_tag("-", class: "UsersForm-cartbutton") %>
                            <% end %>

                            <span class="MenuItem-title">
                                <%= cartitem.quantity %>
                            </span>

                            <%= form_with(url: update_quantity_path(id: cartitem.id, quantity: 1),
                                          method: "PUT") do %>
                                <%= submit_tag("+", class: "UsersForm-Submit") %>
                            <% end %>
                        </div>

                        <span class="MenuItem-price">
                            ₹<%= item.price * cartitem.quantity %>
                        </span>

                    </div>


            <% end %>


        </div>

        <div class="CartSection">

        <div style="display: flex; justify-content: space-between;">
        <p>Total: ₹<%= CartItem.total_amount(@current_user.id) %></p>
                <%= form_with(url: cart_clear_path,
                              method: "DELETE",
                              class: "CartClear") do %>
                    <%= submit_tag("Clear", class: "UsersForm-cartbutton") %>
                <% end %>
        </div>



            <%= form_with(url: "/orders/#{CartItem.total_amount(@current_user.id)}",
                          method: "POST") do |userorder| %>

        <% if @current_user.role == "customer" %>
            <div style="display: flex; justify-content: space-around;margin:10%;">
             Address: -

            <%= userorder.text_area :deliver_address, size: "50x8" %>
            </div>


         <% end %>


        <div style="text-align: center;"><%= userorder.submit "Checkout", class: "UsersForm-Submit" %></div>

        <% end %>


    </div>
    <% else %>
    <div class="CartEmpty-section">
        <p class="MenuTitle">Your Cart is empty</p>
    </div>

    <% end %>





</section>

app/views/menu_categories/_customerclerk.html.erb
<% menu_categories.order(:id).each do |category| %>
    <% if category.status %>
        <div style="background-color:ivory;border-radius:20px;padding:1%;margin: 1% 0;"><div class="MenuCategory-Title">
            <%= category.name %>
            <button onclick="toggler('<%= category.name %>')" class="UsersForm-menubutton"> ☰ </button>


        </div>

        <ul class="MenuCategory-Section" id = "<%= category.name %>" style="display:block;">


            <% MenuItem.order(:id).get_menu_items(category.id).map do |item| %>



                    <li class= "MenuItem">

                        <div class="MenuItem-header">
                            <span class="MenuItem-title"><%= item.name %></span>
                            <span class="MenuItem-price">₹ <%= item.price %></span>
                        <% if item.availability %>
                            <%= form_with(url: "/cart_items?menu_item_id=#{item.id}",
                                          method: "POST") do %>
                                <%= submit_tag("Add to cart",
                                               class: "UsersForm-Submit") %>
                            <% end %>
                        <% else %>
                           <span class="UnavailableText">Unavailable</span>
                        <% end %>
                        </div>

                        <p class="MenuItem-description"><%= item.description %></p>
                    </li>


            <% end %>

        </ul></div>
    <% else %>
        <div style="background-color:ivory;border-radius:20px;padding:1%;margin: 1% 0;"><div class="MenuCategory-Title">
            <%= category.name %> <span class="UnavailableText">Unavailable</span>
        </div>
    <% end %>
<% end %>

app/views/menu_categories/_ownerpage.html.erb
<% menu_categories.order(:id).each do |category| %>

        <div class="MenuCategory-Title">
            <span style="display:flex;align-items:center;">
                <p style="margin-right:15%;"><%= category.name %></p>

                <%= form_with(url: "/menu_categories/#{category.id}",
                              method: "PUT") do %>
            <%= submit_tag(category.status ? "disable" : "enable",
                           class: category.status ? "UsersForm-cartbutton" : "UsersForm-Submit") %>
            <% end %>

            </span>


            <span style="display:flex;margin-right:5%;">

            <%= form_with(url: "/menu_categories/#{category.id}",
                          method: "DELETE") do %>
                                <%= submit_tag("Remove",
                                               class: "UsersForm-menubutton") %>
                            <% end %>
            <button onclick="toggler('<%= category.name %>')" style="margin:0px 10%;" class="UsersForm-menubutton"> ☰ </button>
            </span>
        </div>



        <ul class="MenuCategory-Section" id = "<%= category.name %>" style="display:block;">

            <% MenuItem.order(:id).get_menu_items(category.id).map do |item| %>


                    <li class= "MenuItem">

                        <div class="MenuItem-header">
                            <span class="MenuItem-title"><%= item.name %></span>
                            <span class="MenuItem-price">₹ <%= item.price %></span>

                            <%= form_with(url: "/menu_items/#{item.id}",
                                          method: "PUT") do %>
                                <%= submit_tag(item.availability ? "disable" : "enable",
                                               class: item.availability ? "UsersForm-cartbutton" : "UsersForm-Submit") %>

                            <% end %>
                            <%= form_with(url: "/menu_items/#{item.id}",
                                          method: "DELETE") do %>
                                <%= submit_tag("Remove",
                                               class: "UsersForm-menubutton") %>
                            <% end %>
                        </div>

                        <p class="MenuItem-description"><%= item.description %></p>
                    </li>

            <% end %>

        </ul>

<% end %>

app/views/menu_categories/index.html.erb
<section class="MenuCategoryPage" style= <%= @current_user.role == "owner" ? "width:90%;" : " " %>>
    <p class = "MenuTitle">Menu Today</p>

    <% if @current_user.role == "owner" %>
        <%= render partial: "ownerpage", locals: {
                     menu_categories: MenuCategory.all,
                   } %>
    <% else %>
        <%= render partial: "customerclerk", locals: {
                     menu_categories: MenuCategory.all,
                   } %>
    <% end %>


</section>

<% if @current_user.role != "owner" %>
        <%= render partial: "cartsection", locals: {} %>
<% end %>


<script>
                function toggler(sectionid) {
                var x = document.getElementById(sectionid);
                if (x.style.display === "none") {
                x.style.display = "block";
                } else {
                x.style.display = "none";
                }

                }
                </script>