config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/", to: "home#index"

  get "/menu_categories", to: "menu_categories#index"
  post "/menu_categories", to: "menu_categories#create", as: :create_menu_category
  put "/menu_categories/:id", to: "menu_categories#update"
  delete "/menu_categories/:id", to: "menu_categories#destroy"

  get "/new_menu_item", to: "menu_items#new", as: :new_menu_item
  get "/create_menu_item", to: "menu_items#create", as: :create_menu_item
  put "/menu_items/:id", to: "menu_items#update"
  delete "/menu_items/:id", to: "menu_items#destroy"

  get "cart_items", to: "cart_items#index"
  post "cart_items", to: "cart_items#create"
  delete "/clear_cart_items", to: "cart_items#destroy", as: :cart_clear
  put "/cart_items", to: "cart_items#update", as: :update_quantity

  get "/orders", to: "orders#index"
  post "/orders/:total_amount", to: "orders#create"
  put "/orders/:id", to: "orders#update"

  get "/order_items", to: "order_items#index"
  get "/create_order_item", to: "order_items#create", as: :create_order_item

  resources :users

  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  get "/signout", to: "sessions#destroy", as: :destroy_session

  get "/reports", to: "reports#index", as: :reports
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :menu_category
  has_many :order_items

  validates :name,
            presence: true,
            length: { minimum: 4 }
  validates :price, presence: true
  validates :description, presence: true

  def self.get_menu_items(id)
    where(menu_category_id: id)
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :ensure_current_is_owner

  def new
  end

  def create
    new_item = MenuItem.new(
      menu_category_id: params[:menu_category_id],
      name: params[:name],
      description: params[:description],
      price: params[:price],
      availability: true,
    )

    if new_item.save
      flash[:success] = " Item \'#{params[:name]}\' created."
      redirect_to menu_categories_path
    else
      flash[:error] = new_item.errors.full_messages.join(", ")
      redirect_to new_menu_item_path
    end
  end

  def update
    menuitem = MenuItem.find(params[:id])
    menuitem.availability = !menuitem.availability
    menuitem.save!
    flash[:success] = " Item \'#{menuitem.name}\' made #{menuitem.availability ? "available" : " disabled"} ."
    redirect_to menu_categories_path
  end

  def destroy
    cachename = MenuItem.find(params[:id]).name
    MenuItem.find(params[:id]).destroy
    flash[:success] = " #{cachename} deleted successfully "
    redirect_to menu_categories_path
  end
end

app/views/menu_items/_categories.html.erb
<div style="display:flexbox; margin-left:45%;width:400px">


    <% MenuCategory.order(:id).each do |category| %>
      	<div style="display: flex; margin:3%;max-width:300px;">
									<%= menuitem.radio_button(:category,
                                   "#{category.id}") %>
																		<%= category.name %></div>

		<% end %>

    </div>

</div>

app/views/menu_items/new.html.erb
<main class="MenuItemPage">
	<div class="UsersNew-Title">Add Menu Items
			<%= link_to "Home", "/",
               class: "UsersForm-home" %>
	</div>

	<section class="MenuItemForm">
		<%= form_with(url: create_menu_category_path) do |menuitem| %>


				<p class="UsersForm-section">Select a Category to add items to it or Update Category name</p>

					<div class="MenusForm-section">
						<p>Category: </p>

						<%= render partial: "categories", locals: {
                   menuitem: menuitem,
                 } %>


					</div>
					<div class="UsersForm-section" >
						<p>	New/Update Category: </p>
						<%= menuitem.text_field :newcategory,
                              placeholder: "create or update a category",
                              class: "UsersForm-input" %>
					</div>



					<div class="UsersForm-section">
						<p>	Item Name: </p>
						<%= menuitem.text_field :name,
                              class: "UsersForm-input" %>
					</div>

					<div class="UsersForm-section">
								<p>Price(INR): </p>
						<%= menuitem.number_field :price,
                                class: "UsersForm-input" %>
					</div>

					<div class="UsersForm-section">
						<p>Description:</p>
						<%= menuitem.text_area :description,
                             class: "UsersForm-input" %>
					</div>

					<div class="UsersForm-section">
						<%= menuitem.submit "Confirm Changes",
                          class: "UsersForm-Submit" %>
					</div>

			<% end %>
	</section>



</main>