config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/", to: "home#index"

  get "/menu_categories", to: "menu_categories#index"
  post "/menu_categories", to: "menu_categories#create", as: :create_menu_category
  put "/menu_categories/:id", to: "menu_categories#update"
  delete "/menu_categories/:id", to: "menu_categories#destroy"

  get "/new_menu_item", to: "menu_items#new", as: :new_menu_item
  get "/create_menu_item", to: "menu_items#create", as: :create_menu_item
  put "/menu_items/:id", to: "menu_items#update"
  delete "/menu_items/:id", to: "menu_items#destroy"

  get "cart_items", to: "cart_items#index"
  post "cart_items", to: "cart_items#create"
  delete "/clear_cart_items", to: "cart_items#destroy", as: :cart_clear
  put "/cart_items", to: "cart_items#update", as: :update_quantity

  get "/orders", to: "orders#index"
  post "/orders/:total_amount", to: "orders#create"
  put "/orders/:id", to: "orders#update"

  get "/order_items", to: "order_items#index"
  get "/create_order_item", to: "order_items#create", as: :create_order_item

  resources :users

  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  get "/signout", to: "sessions#destroy", as: :destroy_session

  get "/reports", to: "reports#index", as: :reports
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    if @current_user.role == "owner"
      if params[:date_first].present?
        @orders = Order.where("ordered_at between ? and ?",
                              params[:date_first],
                              DateTime.parse(params[:date_last]) + 1)
      else
        @orders = Order.all
      end
      render "index"
    else
      redirect_to "/"
    end
  end
end

app/views/reports/index.html.erb
<main class="OrderPageMain">
  <p class="OrderTitle">Sales Report</p>


    <div style="margin:2%; padding:2%;"><%= form_with(url: reports_path, method: "GET") do |filterdate| %>

      <section class="OrdersTable-Title" style="border-radius:0;box-shadow:none;">

        <%= filterdate.date_field(:date_first, required: true, class: "FilterOrder-date") %>
        <%= filterdate.date_field(:date_last, required: true, class: "FilterOrder-date") %>
        <%= filterdate.submit("FILTER", class: "UsersForm-Submit") %>
        <%= link_to "Clear Filter", reports_path, class: "UsersForm-menubutton" %>

      </section>

    <% end %>


    <section class="OrdersTable-Title" style="border-radius:0;box-shadow:none;">
      <span>Total Orders: - <span class="OrderItem-price"><%= @orders.count %></span></span>
      <span> Income: - <span class="OrderItem-price">₹<%= @orders.sum(:total_amount) %></span></span>
    </section>

  </div>

  <div class="OrdersTable">
      <div class="OrdersTable-Title">
          <span>Ordered By</span>
          <span>Ordered At</span>
          <span>Delivery Status</span>
          <span>Bill Amount</span>

      </div>

    <% @orders.order(:ordered_at).each do |order| %>
      <div class="OrderItem">
      <span>

        <% if order.online_order %>

          <%= User.find(order.user_id).first_name + " " + User.find(order.user_id).last_name %>

        <% else %>

              Walk-in Customer

        <% end %>

      </span>
      <span class="OrderItem-date">
              <%= order.ordered_at.to_s(:long) %>
      </span>
      <span class="OrderItem-date">
                <%= order.delivered_at ? order.delivered_at.to_s(:short) : "pending delivery" %>
      </span>
      <span>
        <%= link_to "₹#{order.total_amount}", order_items_path(id: order.id), method: "GET", class: "UsersForm-cartbutton" %>
      </span>
      </div>
    <% end %>
  </div>
</main>